[package]
name = "dl-webserver"
version = "0.1.0"
authors = ["epwalsh <epwalsh10@gmail.com>"]
edition = "2018"

[dependencies]
batched-fn = { version = "0.1.2" }
tokio = { version = "0.2.13", features = ["full"] }
tch = { version = "0.1.6" }
rust-bert = { version = "0.5.2" }
exitfailure = { version = "0.5.1" }
